<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyVersion>3.7.5.0</AssemblyVersion>
    <FileVersion>3.7.5.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\Run\Tests\Debug\</OutputPath>
    <NoWarn>0219</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\Run\Tests\Release\</OutputPath>
    <NoWarn>0219</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="xunit">
      <HintPath>..\..\Dependencies\xUnit\xunit.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\System.Data.SQLite.Benchmark\Classes\SQLiteDatabase.cs">
      <Link>Classes\SQLiteDatabase.cs</Link>
    </Compile>
    <Compile Include="..\..\System.Data.SQLite.Benchmark\Classes\SQLiteVdbe.cs">
      <Link>Classes\SQLiteVdbe.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\System.Data.SQLite\System.Data.SQLite.csproj" />
  </ItemGroup>
</Project>