<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\Run\Tests\Debug</OutputPath>
    <ConsolePause>False</ConsolePause>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <Optimize>False</Optimize>
    <OutputPath>..\..\Run\Tests\Release</OutputPath>
    <DefineConstants>RELEASE</DefineConstants>
    <ConsolePause>False</ConsolePause>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.Linq" />
    <Reference Include="nunit.framework">
      <HintPath>..\..\Dependencies\nunit.framework.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="Sql\People.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Sql\Shirts.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Sql\Northwind.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\System.Data.SQLite\System.Data.SQLite.csproj" />
  </ItemGroup>
</Project>