<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Benchmark</RootNamespace>
    <AssemblyName>Benchmark</AssemblyName>
    <StartupObject>Benchmark</StartupObject>
    <ApplicationIcon>C#-SQLite.ico</ApplicationIcon>
    <AssemblyVersion>3.7.7.1</AssemblyVersion>
    <FileVersion>3.7.7.1</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Run\Debug\</OutputPath>
    <NoWarn>0168;0414;0219</NoWarn>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\Run\Release\</OutputPath>
    <DefineConstants>RELEASE</DefineConstants>
    <NoWarn>0168;0414;0219</NoWarn>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CsSqlite\CsSqlite.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
  </ItemGroup>
</Project>